/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.felipe.gestor.view;

import com.felipe.gestor.controller.AlunoController;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author felipe
 */
public class TelaAluno extends javax.swing.JFrame {

    private final AlunoController aController;
    
    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
        aController = new AlunoController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConteudo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jLabelNomeTela = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelFormularioAluno = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldAlunoNome = new javax.swing.JTextField();
        jLabelCurso = new javax.swing.JLabel();
        jTextFieldCursoDescricao = new javax.swing.JTextField();
        jButtonAlunoSalvar = new javax.swing.JButton();
        jButtonAlunoEditar = new javax.swing.JButton();
        jButtonAlunoApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestor de alunos");
        setName("frameAluno"); // NOI18N
        setResizable(false);

        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "codigo", "nome", "curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAlunos.getTableHeader().setReorderingAllowed(false);
        jTableAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlunos);
        if (jTableAlunos.getColumnModel().getColumnCount() > 0) {
            jTableAlunos.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        jLabelNomeTela.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelNomeTela.setText("Alunos cadastrados");

        jPanelFormularioAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Aluno"));

        jLabelNome.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabelNome.setText("Nome");

        jTextFieldAlunoNome.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabelCurso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabelCurso.setText("Curso");

        jTextFieldCursoDescricao.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jButtonAlunoSalvar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonAlunoSalvar.setText("Salvar");
        jButtonAlunoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlunoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormularioAlunoLayout = new javax.swing.GroupLayout(jPanelFormularioAluno);
        jPanelFormularioAluno.setLayout(jPanelFormularioAlunoLayout);
        jPanelFormularioAlunoLayout.setHorizontalGroup(
            jPanelFormularioAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldAlunoNome)
                    .addComponent(jLabelCurso)
                    .addComponent(jTextFieldCursoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jButtonAlunoSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFormularioAlunoLayout.setVerticalGroup(
            jPanelFormularioAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCursoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlunoSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAlunoEditar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonAlunoEditar.setText("Editar");
        jButtonAlunoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlunoEditarActionPerformed(evt);
            }
        });

        jButtonAlunoApagar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonAlunoApagar.setText("Apagar");
        jButtonAlunoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlunoApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConteudoLayout = new javax.swing.GroupLayout(jPanelConteudo);
        jPanelConteudo.setLayout(jPanelConteudoLayout);
        jPanelConteudoLayout.setHorizontalGroup(
            jPanelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormularioAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelConteudoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAlunoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAlunoApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                    .addGroup(jPanelConteudoLayout.createSequentialGroup()
                        .addComponent(jLabelNomeTela)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelConteudoLayout.setVerticalGroup(
            jPanelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormularioAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConteudoLayout.createSequentialGroup()
                        .addComponent(jButtonAlunoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlunoApagar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlunoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlunoSalvarActionPerformed

        this.aController.salvar();
        this.aController.tabelaAluno();
        
    }//GEN-LAST:event_jButtonAlunoSalvarActionPerformed

    private void jTableAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunosMouseClicked
        
        this.aController.selecionaLinha();
        
    }//GEN-LAST:event_jTableAlunosMouseClicked

    private void jButtonAlunoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlunoEditarActionPerformed
        
        this.aController.editar();
        this.aController.tabelaAluno();
        
    }//GEN-LAST:event_jButtonAlunoEditarActionPerformed

    private void jButtonAlunoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlunoApagarActionPerformed
        
        this.aController.apagar();
        this.aController.tabelaAluno();
        
    }//GEN-LAST:event_jButtonAlunoApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaAluno().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlunoApagar;
    private javax.swing.JButton jButtonAlunoEditar;
    private javax.swing.JButton jButtonAlunoSalvar;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeTela;
    private javax.swing.JPanel jPanelConteudo;
    private javax.swing.JPanel jPanelFormularioAluno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableAlunos;
    private javax.swing.JTextField jTextFieldAlunoNome;
    private javax.swing.JTextField jTextFieldCursoDescricao;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.aController.tabelaAluno();
    }

    public JTable getjTableAlunos() {
        return jTableAlunos;
    }

    public void setjTableAlunos(JTable jTableAlunos) {
        this.jTableAlunos = jTableAlunos;
    }

    public JTextField getjTextFieldAlunoNome() {
        return jTextFieldAlunoNome;
    }

    public void setjTextFieldAlunoNome(JTextField jTextFieldAlunoNome) {
        this.jTextFieldAlunoNome = jTextFieldAlunoNome;
    }

    public JTextField getjTextFieldCursoDescricao() {
        return jTextFieldCursoDescricao;
    }

    public void setjTextFieldCursoDescricao(JTextField jTextFieldCursoDescricao) {
        this.jTextFieldCursoDescricao = jTextFieldCursoDescricao;
    }
}
