/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.felipe.gestor.view;

import com.felipe.gestor.controller.CursoController;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author felipe
 */
public class TelaCurso extends javax.swing.JFrame {

    private final CursoController cController;

    /**
     * Creates new form TelaCurso
     */
    public TelaCurso() {
        initComponents();
        cController = new CursoController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCursoConteudo = new javax.swing.JPanel();
        jPanelFormularioCurso = new javax.swing.JPanel();
        jLabelCursoDescricao = new javax.swing.JLabel();
        jTextFieldCursoDescricao = new javax.swing.JTextField();
        jLabelCursoEmenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCursoEmenta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAlunoNome = new javax.swing.JTextField();
        jButtonCursoSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCursos = new javax.swing.JTable();
        jButtonCursoEditar = new javax.swing.JButton();
        jButtonCursoApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("frameCurso"); // NOI18N
        setResizable(false);

        jPanelFormularioCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar curso"));

        jLabelCursoDescricao.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabelCursoDescricao.setText("Descrição");

        jTextFieldCursoDescricao.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabelCursoEmenta.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabelCursoEmenta.setText("Ementa");

        jTextAreaCursoEmenta.setColumns(20);
        jTextAreaCursoEmenta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextAreaCursoEmenta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCursoEmenta);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Alunos");

        jTextFieldAlunoNome.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jButtonCursoSalvar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonCursoSalvar.setText("Novo");
        jButtonCursoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursoSalvarActionPerformed(evt);
            }
        });

        jTableCursos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "codigo", "descricao", "ementa", "aluno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCursos.getTableHeader().setReorderingAllowed(false);
        jTableCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCursos);

        jButtonCursoEditar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonCursoEditar.setText("Editar");
        jButtonCursoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursoEditarActionPerformed(evt);
            }
        });

        jButtonCursoApagar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonCursoApagar.setText("Apagar");
        jButtonCursoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursoApagarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormularioCursoLayout = new javax.swing.GroupLayout(jPanelFormularioCurso);
        jPanelFormularioCurso.setLayout(jPanelFormularioCursoLayout);
        jPanelFormularioCursoLayout.setHorizontalGroup(
            jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelFormularioCursoLayout.createSequentialGroup()
                .addGroup(jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioCursoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCursoDescricao)
                            .addComponent(jLabelCursoEmenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCursoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFormularioCursoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonCursoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCursoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCursoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormularioCursoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelFormularioCursoLayout.setVerticalGroup(
            jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioCursoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCursoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCursoDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCursoEmenta)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanelFormularioCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonCursoEditar)
                    .addComponent(jButtonCursoSalvar)
                    .addComponent(jButtonCursoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelFormularioCursoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCursoApagar, jButtonCursoEditar, jButtonCursoSalvar, jButtonLimpar});

        javax.swing.GroupLayout jPanelCursoConteudoLayout = new javax.swing.GroupLayout(jPanelCursoConteudo);
        jPanelCursoConteudo.setLayout(jPanelCursoConteudoLayout);
        jPanelCursoConteudoLayout.setHorizontalGroup(
            jPanelCursoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCursoConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormularioCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCursoConteudoLayout.setVerticalGroup(
            jPanelCursoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCursoConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormularioCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCursoConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCursoConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCursoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCursoSalvarActionPerformed
      
        this.cController.salvar();
        this.cController.tabelaCurso();
        
    }//GEN-LAST:event_jButtonCursoSalvarActionPerformed

    private void jTableCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCursosMouseClicked
        
        this.cController.selecionaLinha();
        
    }//GEN-LAST:event_jTableCursosMouseClicked

    private void jButtonCursoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCursoEditarActionPerformed
       
        this.cController.editar();
        this.cController.tabelaCurso();
        
    }//GEN-LAST:event_jButtonCursoEditarActionPerformed

    private void jButtonCursoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCursoApagarActionPerformed
       
        this.cController.apagar();
        this.cController.tabelaCurso();
        
    }//GEN-LAST:event_jButtonCursoApagarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCurso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCursoApagar;
    private javax.swing.JButton jButtonCursoEditar;
    private javax.swing.JButton jButtonCursoSalvar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCursoDescricao;
    private javax.swing.JLabel jLabelCursoEmenta;
    private javax.swing.JPanel jPanelCursoConteudo;
    private javax.swing.JPanel jPanelFormularioCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCursos;
    private javax.swing.JTextArea jTextAreaCursoEmenta;
    private javax.swing.JTextField jTextFieldAlunoNome;
    private javax.swing.JTextField jTextFieldCursoDescricao;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.cController.tabelaCurso();
    }

    public JTextArea getjTextAreaCursoEmenta() {
        return jTextAreaCursoEmenta;
    }

    public void setjTextAreaCursoEmenta(JTextArea jTextAreaCursoEmenta) {
        this.jTextAreaCursoEmenta = jTextAreaCursoEmenta;
    }

    public JTextField getjTextFieldAlunoNome() {
        return jTextFieldAlunoNome;
    }

    public void setjTextFieldAlunoNome(JTextField jTextFieldAlunoNome) {
        this.jTextFieldAlunoNome = jTextFieldAlunoNome;
    }

    public JTextField getjTextFieldCursoDescricao() {
        return jTextFieldCursoDescricao;
    }

    public void setjTextFieldCursoDescricao(JTextField jTextFieldCursoDescricao) {
        this.jTextFieldCursoDescricao = jTextFieldCursoDescricao;
    }

    public JTable getjTableCursos() {
        return jTableCursos;
    }

    public void setjTableCursos(JTable jTableCursos) {
        this.jTableCursos = jTableCursos;
    }
}
